In [ ]:
def sum_of_two_numbers(a, b):
    return a + b

result = sum_of_two_numbers(3, 5)
print(f"The sum is: {result}")


The sum is: 8


In [3]:
def sum_of_two_numbers(a, b):
    return a * b

result = sum_of_two_numbers(3, 5)
print(f"The sum is: {result}")

The sum is: 15


In [4]:
def sum_of_two_numbers(a, b):
    return a / b

result = sum_of_two_numbers(3, 5)
print(f"The sum is: {result}")

The sum is: 0.6


In [1]:
def sum_of_two_numbers(a, b):
    return a - b

result = sum_of_two_numbers(3, 5)
print(f"The sum is: {result}")

The sum is: -2


In [2]:
my_list = [1, 2, 3, 4, 5]
print(my_list[2])
print(my_list[3:5])
my_list[0] = 11
print(my_list)


3
[4, 5]
[11, 2, 3, 4, 5]


In [ ]:
class Library:

    def __init__(self,title, author, publication_year):

        self.title=title
        self.author=author
        self.publication_year=publication_year
    def work(self):

        pass

In [ ]:
class Book(Library):
    def __init__(self,title,author,publication_year):
        self.title=title
        self.author=author
        self.publication_year=publication_year
    def checkout(self):
         print(f"{self.title} {self.author} {self.publication_year}")
    def return_item(self):
        print(f"{self.title} {self.author} {self.publication_year}")

In [ ]:
class Book(Library):
    def __init__(self,title,author,publication_year):
        self.title=title
        self.author=author
        self.publication_year=publication_year
    def checkout(self):
         print(f"{self.title} {self.author} {self.publication_year}")
    def return_item(self):
        print(f"{self.title} {self.author} {self.publication_year}")

In [ ]:
class Magazine(Library):
    def __init__(self,title,author,publication_year):
        self.title=title
        self.author=author
        self.publication_year=publication_year
    def return_item(self):
        print(f"{self.title} {self.author} {self.publication_year}")
    def checkout(self):
         print(f"{self.title} {self.author} {self.publication_year}")

In [ ]:
book1=Book("the last lesson","alphonse daudet","1870")
book1.checkout()
book1=Book("the last lesson","alphonse daudet","1870")
book1.return_item()

the last lesson alphonse daudet 1870
the last lesson alphonse daudet 1870


In [ ]:
magazine1=Magazine("the lost spring","Anees Jung","2005")
magazine1.return_item()
magazine1=Magazine("the lost spring","Anees Jung","2005")
magazine1.checkout()

the lost spring Anees Jung 2005
the lost spring Anees Jung 2005


In [ ]:
import pandas as pd

In [ ]:
student={
    "name":['nikhil','jyoti'],
    "class":['11','10'],
    "score":['80%','75%']
}
ha=pd.DataFrame(student)
print(ha)


     name class score
0  nikhil    11   80%
1   jyoti    10   75%


In [ ]:
mydataset={
    "villager":['jarthal','raliyawas','nangal saliya'],
    "city":['rewari','jaipur','alwar']
}
sv=pd.DataFrame(mydataset)
print(sv)

        villager    city
0        jarthal  rewari
1      raliyawas  jaipur
2  nangal saliya   alwar


In [ ]:
mydataset={
    "Duration":{
        0:60,
        1:45,
        2:35,
        3:60,
        4:60
    },
    "pulse":{
        0:102,
        1:112,
        2:117,
        3:103,
        4:109
    }
}
sd=pd.DataFrame(mydataset)
print(sd)

   Duration  pulse
0        60    102
1        45    112
2        35    117
3        60    103
4        60    109


In [ ]:
a=[1,2,3,4,5]
pritam=pd.Series(a)
print(pritam)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
data = {
      "student":{
    "0":1,
    "1":2,
    "2":3,
    "3":4,
    "4":5,
    "5":6
  },
      "name":{
    "0":"nikhil",
    "1":"jyoti",
    "2":"garvi",
    "3":"mamta",
    "4":"mohit",
    "5":"naman"
  },
      "roll no":{
    "0":20,
    "1":21,
    "2":22,
    "3":23,
    "4":24,
    "5":25
  },
      "possition":{
    "0":"A",
    "1":"A+",
    "2":"B",
    "3":"B+",
    "4":"B+",
    "5":"A"
  },

}

df = pd.DataFrame(data)

print(df)


   student    name  roll no possition
0        1  nikhil       20         A
1        2   jyoti       21        A+
2        3   garvi       22         B
3        4   mamta       23        B+
4        5   mohit       24        B+
5        6   naman       25         A


In [15]:
for p in range(2,3):

    for v in range(1,11):

        print(p, "*", v, "=", p*v)



2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20



In [16]:
for numbers in range(2, 18):
    is_prime = True
    for h in range(2, int(numbers ** 0.2) + 1):
        if numbers % h == 0:
            is_prime = False
            break
    if is_prime:
        print(numbers, "is a prime number")
    else:
        print(numbers, "is not a prime number")

2 is a prime number
3 is a prime number
4 is a prime number
5 is a prime number
6 is a prime number
7 is a prime number
8 is a prime number
9 is a prime number
10 is a prime number
11 is a prime number
12 is a prime number
13 is a prime number
14 is a prime number
15 is a prime number
16 is a prime number
17 is a prime number


In [20]:
for pri in range(1,5):
    factorial = 1
    for n in range(1, pri + 1):
        factorial *= n
    print("Factorial of", pri, "is", factorial)

Factorial of 1 is 1
Factorial of 2 is 2
Factorial of 3 is 6
Factorial of 4 is 24


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [25]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
arr2.shape

(2, 4)

In [27]:
arr2.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [28]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [29]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
2+np.ones((4,4))

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [ ]:
class Person:
    def __init__(self,name):
        self.name=name

    def display_info(self):
        print(f"Name is : {self.name}")

In [ ]:
class Student(Person):
    def __init__(self,name,grade):
        super().__init__(name)
        self.grade=grade

    def display_info(self):
        super().display_info()
        print(f"Grade    is : {self.grade}")


In [ ]:
student1= Student("pritam","A")
student1.display_info()

Name is : pritam
Grade is : A


In [ ]:
def is_even(num):
    if num % 2 == 0:
      return('even')
    else:
      return('odd')

is_even(7)

'odd'

In [ ]:
def shout(text):
    return text.upper()

def whisper(text):
    return text.lower()

def greet(func):
    greeting = func("Hi, I am created by a function passed as an argument.")
    print(greeting)

greet(shout)
greet(whisper)

HI, I AM CREATED BY A FUNCTION PASSED AS AN ARGUMENT.
hi, i am created by a function passed as an argument.
